# fly.toml app configuration file generated for minecraft-telegram-bot on 2025-01-27T00:00:00Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "minecraft-telegram-bot"
primary_region = "fra"  # Frankfurt - قريب من الشرق الأوسط
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[mounts]]
  source = "bot_data"
  destination = "/app/data"

[deploy]
  release_command = "echo 'Starting Minecraft Telegram Bot...'"

[processes]
  app = "node index.js"

# إعدادات إعادة التشغيل التلقائي
[restart]
  policy = "always"
