[phases.setup]
nixPkgs = ['nodejs_22', 'npm', 'python3', 'gcc', 'gnumake', 'cmake']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build --if-present']

[start]
cmd = 'npm start'
